version: '3.4'

services:
  cashflow.presentation:
    depends_on:
      - cashflow.database
    image: ${DOCKER_REGISTRY-}cashflow-presentation
    build:
      context: .
      dockerfile: CashFlow.Presentation/Dockerfile

  cashflow.jobs:
    depends_on:
      - cashflow.presentation
    image: ${DOCKER_REGISTRY-}cashflow-jobs
    build:
      context: .
      dockerfile: CashFlow.Jobs/Dockerfile
      
  cashflow.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "senha@1234"
      TZ: "America/Sao_Paulo"
    ports:
      - "1433:1433"
    volumes:
      - ${APPDATA}/cashflow/database:/var/opt/mssql/data
    container_name: Cashflow.Database

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    container_name: Cashflow.Elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: Cashflow.Kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch